/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DayAndNight
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// DayAndNightSettingTab.ts
var import_obsidian = require("obsidian");
var DayAndNightSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.DARK_COLOR_SCHEME_KEY = "obsidian";
    this.LIGHT_COLOR_SCHEME_KEY = "moonstone";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Scheduler configuration").setHeading();
    this.addPluginToggleSetting();
    if (this.plugin.settings.pluginEnabled) {
      this.addDaySettings();
      this.addNightSettings();
    }
  }
  addPluginToggleSetting() {
    new import_obsidian.Setting(this.containerEl).setName("Enable Day and Night").addToggle((value) => {
      value.setValue(this.plugin.settings.pluginEnabled);
      value.onChange((value2) => __async(this, null, function* () {
        this.plugin.settings.pluginEnabled = value2;
        yield this.plugin.saveData(this.plugin.settings);
        this.display();
      }));
    });
  }
  addNightSettings() {
    new import_obsidian.Setting(this.containerEl).setName("Night Color Scheme").setDesc("Select a Night Color Scheme").addDropdown(
      (dropdown) => dropdown.addOption(this.LIGHT_COLOR_SCHEME_KEY, "Light").addOption(this.DARK_COLOR_SCHEME_KEY, "Dark").setValue(this.plugin.settings.nightColorScheme).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.nightColorScheme = value;
        yield this.plugin.saveData(this.plugin.settings);
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Night Theme").setDesc("Select a Night Theme").addDropdown(
      (dropdown) => dropdown.addOptions(this.getAllCommunityThemes()).setValue(this.plugin.settings.nightTheme).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.nightTheme = value;
        yield this.plugin.saveData(this.plugin.settings);
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Night Start Time").setDesc("24-hour format").addMomentFormat((format) => {
      format.setDefaultFormat("HH:mm").setPlaceholder("HH:mm").setValue(this.plugin.settings.nightTime).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.nightTime = value;
        yield this.plugin.saveData(this.plugin.settings);
      }));
    });
  }
  addDaySettings() {
    new import_obsidian.Setting(this.containerEl).setName("Day Color Scheme").setDesc("Select a Day Color Scheme").addDropdown(
      (dropdown) => dropdown.addOption(this.LIGHT_COLOR_SCHEME_KEY, "Light").addOption(this.DARK_COLOR_SCHEME_KEY, "Dark").setValue(this.plugin.settings.dayColorScheme).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.dayColorScheme = value;
        yield this.plugin.saveData(this.plugin.settings);
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Day Theme").setDesc("Select a Day Theme").addDropdown(
      (dropdown) => dropdown.addOptions(this.getAllCommunityThemes()).setValue(this.plugin.settings.dayTheme).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.dayTheme = value;
        yield this.plugin.saveData(this.plugin.settings);
      }))
    );
    new import_obsidian.Setting(this.containerEl).setName("Day Start Time").setDesc("24-hour format").addMomentFormat((format) => {
      format.setDefaultFormat("HH:mm").setPlaceholder("HH:mm").setValue(this.plugin.settings.dayTime).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.dayTime = value;
        yield this.plugin.saveData(this.plugin.settings);
      }));
    });
  }
  getAllCommunityThemes() {
    const themes = Object.keys(this.app.customCss.themes);
    const communityThemesRecord = { "": "" };
    for (const theme of themes) {
      communityThemesRecord[theme] = theme;
    }
    return communityThemesRecord;
  }
};

// DefaultSettings.ts
var DefaultSettings = {
  pluginEnabled: false,
  currentTheme: "",
  currentColorScheme: "moonstone",
  dayColorScheme: "moonstone",
  dayTime: "10:00",
  dayTheme: "",
  nightColorScheme: "obsidian",
  nightTime: "15:00",
  nightTheme: "",
  pauseThemeToggle: false
};

// main.ts
var moment = import_obsidian2.moment;
var DayAndNight = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.settings.pauseThemeToggle = false;
      yield this.saveSettings();
      yield this.updateTheme();
      yield this.addRibbonIconToToolbar();
      this.addSettingTab(new DayAndNightSettingTab(this.app, this));
      this.registerDomEvent(activeDocument, "click", (evt) => {
      });
      this.registerInterval(
        window.setInterval(() => {
          void this.updateTheme();
        }, 1e4)
      );
    });
  }
  onunload() {
  }
  updateTheme() {
    return __async(this, null, function* () {
      if (!this.settings.pluginEnabled) {
        return;
      }
      const { themeToApply, colorSchemeToApply } = this.getThemeToApply();
      if (!this.settings.pauseThemeToggle && (this.getCurrentTheme() != themeToApply || this.getCurrentColorScheme() != colorSchemeToApply)) {
        yield this.setTheme(themeToApply, colorSchemeToApply);
      } else if (this.getCurrentTheme() == themeToApply || this.getCurrentColorScheme() == colorSchemeToApply) {
        yield this.saveSettings();
      }
    });
  }
  setTheme(currentTheme, currentColorScheme) {
    return __async(this, null, function* () {
      this.setCurrentColorScheme(currentColorScheme);
      this.setCurrentTheme(currentTheme);
      this.app.workspace.trigger("css-change");
      yield this.saveSettings();
    });
  }
  getThemeToApply() {
    const dayDate = moment(this.settings.dayTime, moment.HTML5_FMT.TIME).toDate();
    const nightDate = moment(this.settings.nightTime, moment.HTML5_FMT.TIME).toDate();
    let themeToApply = this.getCurrentTheme();
    let colorSchemeToApply = this.getCurrentColorScheme();
    if (moment().isAfter(dayDate) && moment().isBefore(nightDate)) {
      themeToApply = this.settings.dayTheme;
      colorSchemeToApply = this.settings.dayColorScheme;
    } else if (moment().isSameOrAfter(nightDate) || moment().isBefore(dayDate)) {
      themeToApply = this.settings.nightTheme;
      colorSchemeToApply = this.settings.nightColorScheme;
    }
    return { themeToApply, colorSchemeToApply };
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DefaultSettings, yield this.loadData());
    });
  }
  addRibbonIconToToolbar() {
    return __async(this, null, function* () {
      const ribbonIcon = this.addRibbonIcon(this.getRibbonIconName(), "Toggle Theme", () => __async(this, null, function* () {
        yield this.toggleTheme();
        this.settings.pauseThemeToggle = true;
        yield this.saveSettings();
        (0, import_obsidian2.setIcon)(ribbonIcon, this.getRibbonIconName());
      }));
    });
  }
  getRibbonIconName() {
    return this.isCurrentThemeNightTheme() ? "sun" : "moon";
  }
  toggleTheme() {
    return __async(this, null, function* () {
      if (this.isCurrentThemeNightTheme()) {
        yield this.setTheme(this.settings.dayTheme, this.settings.dayColorScheme);
      } else {
        yield this.setTheme(this.settings.nightTheme, this.settings.nightColorScheme);
      }
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  getCurrentTheme() {
    return this.app.customCss.theme;
  }
  setCurrentTheme(currentTheme) {
    this.app.customCss.setTheme(currentTheme);
    this.settings.currentTheme = currentTheme;
  }
  getCurrentColorScheme() {
    return this.app.vault.getConfig("theme");
  }
  setCurrentColorScheme(currentColorScheme) {
    this.app.setTheme(currentColorScheme);
    this.settings.currentColorScheme = currentColorScheme;
    this.app.vault.setConfig("theme", currentColorScheme);
  }
  isCurrentThemeNightTheme() {
    const currentTheme = this.getCurrentTheme();
    const currentColorScheme = this.getCurrentColorScheme();
    return currentTheme == this.settings.nightTheme && currentColorScheme == this.settings.nightColorScheme;
  }
};

/* nosourcemap */